version: '3'

services:

  mongo_odm:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DB_CONFIGS=tests/fixtures/db_configs
    container_name: mongo_odm

  mongo:
    image: mongo:3.6.0
    container_name: mongo


networks:
  default:
    driver: bridge